"""Deterministically generate a safe, traceable Python implementation scaffold."""
from __future__ import annotations

import keyword
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

from src.spec_analyzer import analyze_spec


def _identifier(value: str) -> str:
    """Convert an action extracted from a spec into a safe Python method name."""
    name = re.sub(r"[^a-zA-Z0-9_]", "_", value.lower()).strip("_") or "handle"
    if name[0].isdigit() or keyword.iskeyword(name):
        name = f"handle_{name}"
    return name


def _class_name(feature: str) -> str:
    words = re.findall(r"[A-Za-z0-9]+", feature)
    return "".join(word.capitalize() for word in words) + "Implementation"


def render_scaffold(plan: dict[str, Any]) -> str:
    """Render Python source from a spec-analysis plan without executing code."""
    action_scenarios: dict[str, list[str]] = defaultdict(list)
    for task in plan["tasks"]:
        actions = task["actions"] or [f"handle_{task['id'].lower()}"]
        for action in actions:
            action_scenarios[_identifier(action)].append(task["scenario"])

    class_name = _class_name(plan["feature"])
    lines = [
        '"""Generated by SpecGuard. Complete the marked methods before production use."""',
        "from typing import Any",
        "",
        "",
        f"class {class_name}:",
        f'    """Traceable implementation scaffold for: {plan["feature"]}."""',
        "",
        "    def __init__(self) -> None:",
        "        self._state: dict[str, Any] = {}",
    ]

    for action, scenarios in sorted(action_scenarios.items()):
        lines.extend(["", f"    # Traces to: {', '.join(repr(name) for name in scenarios)}"])
        lines.extend([
            f"    def {action}(self, **payload: Any) -> None:",
            f'        """Implement the `{action}` action from the feature specification."""',
            "        raise NotImplementedError(",
            f'            "Implement `{action}` for: {", ".join(scenarios)}"',
            "        )",
        ])

    return "\n".join(lines) + "\n"


def generate_scaffold(spec_path: str, output_path: str, overwrite: bool = False) -> dict[str, Any]:
    """Analyze a feature file and write its traceable Python scaffold atomically."""
    target = Path(output_path)
    if target.exists() and not overwrite:
        raise FileExistsError(f"Refusing to overwrite existing file: {target}")

    plan = analyze_spec(spec_path)
    source = render_scaffold(plan)
    target.parent.mkdir(parents=True, exist_ok=True)
    temporary = target.with_suffix(target.suffix + ".tmp")
    temporary.write_text(source, encoding="utf-8")
    temporary.replace(target)

    return {
        "output": str(target),
        "feature": plan["feature"],
        "scenarios": plan["scenarios_count"],
        "actions": sorted({action for task in plan["tasks"] for action in task["actions"]}),
    }
